CREATE TABLE Kullanicilar (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    isim VARCHAR(30) NOT NULL,
    soyisim VARCHAR(30) NOT NULL,
    email VARCHAR(50),
    kayit_tarihi TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)